# This is a YAML config file for iFireTracker project

# Web server variables
url:
  s3_bucket_name: 'data472-rna104-jarrd-hdd'
  auth_server_url: 'http://13.239.55.4'

path:
  csv_s3_filename: "ifiretracker_data/csv/fire_risk_per_land_use_area.csv"
  html_s3_filename: "ifiretracker_data/html/fire_risk_map.html"
  csv_local_path: "data/csv/fire_risk_per_land_use_area.csv"
  html_local_path: "data/html/fire_risk_map.html"

system:
  # Set the maximum allowed size for HTTP requests to 20 MB (20 * 1024 * 1024)
  max_content_length: "20971520"
  
