# This is a YAML config file for iFireTracker project

# Model server variables

log: "logs/model_execution.log"
csv_s3_filename: "ifiretracker_data/csv/fire_risk_per_land_use_area.csv"
html_s3_filename: "ifiretracker_data/html/fire_risk_map.html"
csv_output_local_path: "model/data/output/csv/fire_risk_per_land_use_area.csv"
html_output_local_path: "model/data/output/html/fire_risk_map.html"
csv_input_fire_risk: "model/data/input/fire_risk_per_polygon.csv"
csv_input_weather_stations: "model/data/input/canterbury_weather_stations.csv"
csv_input_merged_land_stations: "model/data/input/merged/land_use_areas_per_station.csv"
input_fire_risk_prefix: "model/data/input/everyday_data/"
shx_input_land_use: "model/data/input/lucas-nz-land-use-map-1990-2008-2012-2016-v011.shx"
