# This is a YAML config file for iFireTracker project

# Auth server variables

db_name: "<your_db_name>"
db_user: "<your_db_user>"
db_password: "<your_db_password>"
db_host: "<your_db_host>"
secret_key: "<your_secret_key>"
